<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0CM47fV' shared service.

return $this->privates['.service_locator.0CM47fV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'salleRepository' => ['privates', 'App\\Repository\\SalleRepository', 'getSalleRepositoryService.php', true],
]);
