<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UqkERCT' shared service.

return $this->privates['.service_locator.UqkERCT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'classe' => ['privates', '.errored..service_locator.UqkERCT.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.UqkERCT": it references class "App\\Entity\\Classe" but no such service exists.'],
]);
