<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.q3OhSGY' shared service.

return $this->privates['.service_locator.q3OhSGY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'eleve' => ['privates', '.errored..service_locator.q3OhSGY.App\\Entity\\Eleve', NULL, 'Cannot autowire service ".service_locator.q3OhSGY": it references class "App\\Entity\\Eleve" but no such service exists.'],
]);
