<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Salle extends \App\Entity\Salle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'classe', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'eleves', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'inscriptions', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'pansions'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'classe', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'eleves', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'inscriptions', '' . "\0" . 'App\\Entity\\Salle' . "\0" . 'pansions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Salle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle(string $libelle): \App\Entity\Salle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse(): ?\App\Entity\Classe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', []);

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse(?\App\Entity\Classe $classe): \App\Entity\Salle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', [$classe]);

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEleves(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEleves', []);

        return parent::getEleves();
    }

    /**
     * {@inheritDoc}
     */
    public function addElefe(\App\Entity\Eleve $elefe): \App\Entity\Salle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addElefe', [$elefe]);

        return parent::addElefe($elefe);
    }

    /**
     * {@inheritDoc}
     */
    public function removeElefe(\App\Entity\Eleve $elefe): \App\Entity\Salle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeElefe', [$elefe]);

        return parent::removeElefe($elefe);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getInscriptions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscriptions', []);

        return parent::getInscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function addInscription(\App\Entity\Inscription $inscription): \App\Entity\Salle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInscription', [$inscription]);

        return parent::addInscription($inscription);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInscription(\App\Entity\Inscription $inscription): \App\Entity\Salle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInscription', [$inscription]);

        return parent::removeInscription($inscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getPansions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPansions', []);

        return parent::getPansions();
    }

    /**
     * {@inheritDoc}
     */
    public function addPansion(\App\Entity\Pansion $pansion): \App\Entity\Salle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPansion', [$pansion]);

        return parent::addPansion($pansion);
    }

    /**
     * {@inheritDoc}
     */
    public function removePansion(\App\Entity\Pansion $pansion): \App\Entity\Salle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePansion', [$pansion]);

        return parent::removePansion($pansion);
    }

}
