<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.lM8B4sw' shared service.

return $this->privates['.service_locator.lM8B4sw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'salle' => ['privates', '.errored..service_locator.lM8B4sw.App\\Entity\\Salle', NULL, 'Cannot autowire service ".service_locator.lM8B4sw": it references class "App\\Entity\\Salle" but no such service exists.'],
]);
