<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ClasseController::delete' => ['privates', '.service_locator.UqkERCT', 'get_ServiceLocator_UqkERCTService.php', true],
    'App\\Controller\\ClasseController::edit' => ['privates', '.service_locator.UqkERCT', 'get_ServiceLocator_UqkERCTService.php', true],
    'App\\Controller\\ClasseController::index' => ['privates', '.service_locator.0Ndku4i', 'get_ServiceLocator_0Ndku4iService.php', true],
    'App\\Controller\\ClasseController::show' => ['privates', '.service_locator.UqkERCT', 'get_ServiceLocator_UqkERCTService.php', true],
    'App\\Controller\\EleveController::delete' => ['privates', '.service_locator.q3OhSGY', 'get_ServiceLocator_Q3OhSGYService.php', true],
    'App\\Controller\\EleveController::edit' => ['privates', '.service_locator.q3OhSGY', 'get_ServiceLocator_Q3OhSGYService.php', true],
    'App\\Controller\\EleveController::index' => ['privates', '.service_locator.Jfpj27g', 'get_ServiceLocator_Jfpj27gService.php', true],
    'App\\Controller\\EleveController::show' => ['privates', '.service_locator.q3OhSGY', 'get_ServiceLocator_Q3OhSGYService.php', true],
    'App\\Controller\\SalleController::delete' => ['privates', '.service_locator.lM8B4sw', 'get_ServiceLocator_LM8B4swService.php', true],
    'App\\Controller\\SalleController::edit' => ['privates', '.service_locator.lM8B4sw', 'get_ServiceLocator_LM8B4swService.php', true],
    'App\\Controller\\SalleController::index' => ['privates', '.service_locator.0CM47fV', 'get_ServiceLocator_0CM47fVService.php', true],
    'App\\Controller\\SalleController::sectiona' => ['privates', '.service_locator.0CM47fV', 'get_ServiceLocator_0CM47fVService.php', true],
    'App\\Controller\\SalleController::sectionb' => ['privates', '.service_locator.0CM47fV', 'get_ServiceLocator_0CM47fVService.php', true],
    'App\\Controller\\SalleController::sectionf' => ['privates', '.service_locator.0CM47fV', 'get_ServiceLocator_0CM47fVService.php', true],
    'App\\Controller\\SalleController::show' => ['privates', '.service_locator.lM8B4sw', 'get_ServiceLocator_LM8B4swService.php', true],
    'App\\Controller\\ClasseController:delete' => ['privates', '.service_locator.UqkERCT', 'get_ServiceLocator_UqkERCTService.php', true],
    'App\\Controller\\ClasseController:edit' => ['privates', '.service_locator.UqkERCT', 'get_ServiceLocator_UqkERCTService.php', true],
    'App\\Controller\\ClasseController:index' => ['privates', '.service_locator.0Ndku4i', 'get_ServiceLocator_0Ndku4iService.php', true],
    'App\\Controller\\ClasseController:show' => ['privates', '.service_locator.UqkERCT', 'get_ServiceLocator_UqkERCTService.php', true],
    'App\\Controller\\EleveController:delete' => ['privates', '.service_locator.q3OhSGY', 'get_ServiceLocator_Q3OhSGYService.php', true],
    'App\\Controller\\EleveController:edit' => ['privates', '.service_locator.q3OhSGY', 'get_ServiceLocator_Q3OhSGYService.php', true],
    'App\\Controller\\EleveController:index' => ['privates', '.service_locator.Jfpj27g', 'get_ServiceLocator_Jfpj27gService.php', true],
    'App\\Controller\\EleveController:show' => ['privates', '.service_locator.q3OhSGY', 'get_ServiceLocator_Q3OhSGYService.php', true],
    'App\\Controller\\SalleController:delete' => ['privates', '.service_locator.lM8B4sw', 'get_ServiceLocator_LM8B4swService.php', true],
    'App\\Controller\\SalleController:edit' => ['privates', '.service_locator.lM8B4sw', 'get_ServiceLocator_LM8B4swService.php', true],
    'App\\Controller\\SalleController:index' => ['privates', '.service_locator.0CM47fV', 'get_ServiceLocator_0CM47fVService.php', true],
    'App\\Controller\\SalleController:sectiona' => ['privates', '.service_locator.0CM47fV', 'get_ServiceLocator_0CM47fVService.php', true],
    'App\\Controller\\SalleController:sectionb' => ['privates', '.service_locator.0CM47fV', 'get_ServiceLocator_0CM47fVService.php', true],
    'App\\Controller\\SalleController:sectionf' => ['privates', '.service_locator.0CM47fV', 'get_ServiceLocator_0CM47fVService.php', true],
    'App\\Controller\\SalleController:show' => ['privates', '.service_locator.lM8B4sw', 'get_ServiceLocator_LM8B4swService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
