<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHyc3Iwi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHyc3Iwi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHyc3Iwi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHyc3Iwi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHyc3Iwi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Hyc3Iwi',
    'container.build_id' => '6d18e833',
    'container.build_time' => 1565030409,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHyc3Iwi');
