<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2kQrXP9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2kQrXP9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2kQrXP9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2kQrXP9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2kQrXP9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2kQrXP9',
    'container.build_id' => '1ba8a58f',
    'container.build_time' => 1564940943,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2kQrXP9');
